### ISSUE TITLE
Failed to activate the atom-ide-outline package

### ISSUE THREAD

**Issue by debugDS** [atom-community/atom-ide-outline#81]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0-nightly11 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: [atom-ide-outline](https://github.com/atom-ide-community/atom-ide-outline) package 1.16.0

### Stack Trace

Failed to activate the atom-ide-outline package

```
At Cannot set property 'index' of undefined

TypeError: Cannot set property 'index' of undefined
    at Pane.addItem (/packages/tab-smart-sort/lib/tab-smart-sort.coffee:69:3)
    at /packages/atom-ide-outline/dist/main.js:15:77466)
    at Object.exports.activate (/packages/atom-ide-outline/dist/main.js:15:79073)
    at Package.activateNow (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:3451707)
    at /Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:1185167)
    at Emitter.emit (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:1186608)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:386261)
    at /Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:385012
```

### Commands

```
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-color-the-tag-name 1.14.0 
atom-html-preview 0.2.6 
atom-ide-base 2.1.6 
atom-ide-datatip 0.23.1 
atom-ide-definitions 0.4.0 
atom-ide-hyperclick 1.0.9 
atom-ide-markdown-service 1.6.0 
atom-ide-outline 1.16.0 
atom-ide-signature-help 0.14.1 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
atom-notes 1.23.0 
atom-oss-license 1.1.2 
atom-runner 2.7.1 
atomatigit 1.5.5 
autoclose-html 0.23.0 
autocomplete-clang 0.13.1 
autocomplete-emojis 2.5.0 
box-edit 0.1.3 
build 0.70.0 
busy-signal 2.0.1 
change-case 0.6.5 
color-picker 2.3.0 
compare-files 0.8.1 
copy-as-rtf 0.9.3 
copy-with-style 1.1.0 
copy-with-syntax 0.0.3 
count-word 0.2.3 
dark-one-dark-syntax 2.3.0 
darker-one-dark-syntax 1.1.0 
dash 1.7.1 
dash-on-cursor 0.1.0 
delete-lines 0.5.0 
docblockr 0.13.7 
docksend 1.3.0 
document-outline 2.1.2 
escape-utils 0.5.3 
expand-region 0.5.0 
expand-selection-to-quotes 0.11.0 
figlet 0.5.4 
file-icons 2.1.46 
find-selection 0.16.0 
git-history 3.3.0 
goto-last-edit 0.3.3 
hard-wrap 1.7.1 
hey-pane 1.2.0 
highlight-selected 0.17.0 
hyperlink-hyperclick 3.0.2 
ide-csharp 0.6.2 
ide-css 0.3.5 
ide-html 0.6.2 
ide-php 0.7.18 
ide-python 1.7.2 
ide-typescript 0.9.1 
import-sf-mono 1.0.1 
indentation-jumper 0.1.2 
intentions 1.1.5 
keybinding-cheatsheet 0.1.1 
language-diff 0.7.0 
language-ini 1.23.0 
language-latex 1.2.0 
language-swift 0.5.0 
last-cursor-position 0.9.3 
linter 3.3.0 
linter-coffeelint 2.0.66 
linter-csslint 2.0.6 
linter-gcc 0.9.0 
linter-jshint 3.1.19 
linter-shellcheck 1.6.0 
linter-stylelint 4.5.1 
linter-swiftlint 1.3.1 
linter-ui-default 3.1.0 
markdown-pdf 2.3.3 
markdown-preview-enhanced 0.18.6 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.1 
markdown-toc 0.4.2 
markdown-writer 2.11.11 
merge-conflicts 1.4.5 
minimap 4.39.7 
minimap-autohider 1.7.0 
minimap-bookmarks 0.4.6 
minimap-cursorline 1.0.2 
minimap-find-and-replace 5.0.8 
minimap-git-diff 4.3.6 
minimap-highlight-selected 4.6.5 
minimap-linter 2.2.2 
minimap-selection 4.5.4 
minimap-split-diff 0.3.7 
monokai 0.27.0 
monokai-one-dark-vivid-syntax 1.6.0 
omnisharp-atom 0.31.2 
one-dark-material-syntax 1.0.3 
one-dark-vivid-syntax 1.8.1 
open-files 0.8.4 
open-in-app 1.0.1 
open-in-sourcetree 0.2.0 
open-recent 5.0.0 
open-this 0.5.0 
pandoc 0.2.2 
pdf-view 0.72.0 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
project-manager 3.3.8 
revert-buffer 0.6.0 
scratch 1.3.0 
script 3.29.3 
show-in-system 0.4.0 
simple-align 0.2.0 
sort-lines 0.19.0 
sourcerer 2.0.0 
split-diff 1.6.1 
structure-view 0.2.1 
Sublime-Style-Column-Selection 1.7.5 
swackets 0.35.0 
tab-smart-sort 0.3.0 
tabs-to-spaces 1.0.5 
title-case 0.4.0 
todo-show 2.3.2 
tool-bar 1.4.2 
tool-bar-main 0.0.12 
tool-bar-mio 0.0.10 
tree-view-filter 0.5.5 
unsaved-changes 0.1.0 
```

**Comment by aminya** [comment]
This is a connection issue. Please redownload
```
apm install atom-ide-outline
```

**Comment by debugDS** [comment]
Thanks!
