### ISSUE TITLE
Failed to activate the atom-ide-outline package

### ISSUE THREAD

**Issue by ddd** [atom-community/atom-ide-outline#87]
[Enter steps to reproduce:]

1. Install this using Install Package.
2. Let the package install dependencies.
3. Wait for the error to appear.

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-ide-outline](https://github.com/atom-ide-community/atom-ide-outline) package 1.17.0

### Stack Trace

Failed to activate the atom-ide-outline package

```
At Cannot set property 'index' of undefined

TypeError: Cannot set property 'index' of undefined
    at Pane.addItem (/packages/tab-smart-sort/lib/tab-smart-sort.coffee:69:3)
    at /packages/atom-ide-outline/dist/main.js:1:9050)
    at Object.exports.activate (/packages/atom-ide-outline/dist/main.js:1:10070)
    at Package.activateNow (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658881)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:383936
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:383898)
    at /packages/atom-ide-base/node_modules/atom-package-deps/lib/index.js:850:32
    at Array.map (<anonymous>)
    at Object.handleComplete (/packages/atom-ide-base/node_modules/atom-package-deps/lib/index.js:848:32)
    at Object.install (/packages/atom-ide-base/node_modules/atom-package-deps/lib/index.js:982:8)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

### Commands

```
     -7:55 command-palette:toggle (div.tool-panel.tree-view)
     -7:51.1.0 core:confirm (input.hidden-input)
     -7:51.1.0 settings-view:install-packages-and-themes (div.tool-panel.tree-view)
     -4:35.9.0 typescript:activate (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui.teletype-Authenticated)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-everydayrails-rspec 0.5.0 
atom-ide-base 2.3.5 
atom-ide-datatip 0.23.4 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.9 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.0.0 
atom-ide-outline 1.17.0 
atom-ide-signature-help 0.15.2 
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-smart-path-autocomplete 0.1.0 
atom-smart-template 0.3.2 
atom-typescript 14.1.2 
autocomplete-paths 2.12.18 
build 0.70.0 
build-dockerfile 1.0.1 
build-gradle 0.6.0 
build-tools 4.5.13 
busy-signal 2.0.1 
docker 0.8.0 
es6-javascript 1.0.0 
go-to-definition-rails 2.2.0 
hey-pane 1.2.0 
html-to-css 0.2.2 
Hydrogen 2.14.7 
ide-html 0.6.2 
intentions 1.1.5 
javascript-drag-import 0.1.13 
javascript-snippets 1.2.1 
language-docker 1.1.8 
language-freebasic 0.0.10 
language-smarty 1.8.0 
linter 3.3.0 
linter-docker 0.3.2 
linter-eslint 8.5.5 
linter-tidy 2.4.0 
linter-ui-default 3.2.4 
open-in-browser 0.5.2 
rails-partials 0.9.2 
rails-rspec 0.3.2 
rails-snippets 2.26.0 
rails-transporter 1.7.1 
railscast 2.0.2 
railscast-theme 0.4.0 
reload-button 0.1.0 
smart-tab-name 1.0.5 
tab-smart-sort 0.3.0 
teletype 0.13.4 
visual-rails-generator 0.1.0 
```

**Comment by aminya** [comment]
This is a connection issue. Please re-download:
```
apm uninstall atom-ide-outline
apm install atom-ide-outline
```

**Comment by ddd** [comment]
ok how do i do that from within atom?

**Comment by ddd** [comment]
I removed the package and reinstalled the package and its still doing it.

**Comment by aminya** [comment]
The error is thrown from `tab-smart-sort`. Could you disable that?

**Comment by ddd** [comment]
That fixed it. Thank you!
